Final-kk/AlbumsApp/Models/Studio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AlbumsApp.Models
{
    public class Studio
    {
        public int StudioId { get; set; }
        [Required(ErrorMessage = "Studio name is required.")]
        [StringLength(64)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Website name is required.")]
        [Url]
        public string Url { get; set; }
        [Required(ErrorMessage = "Address is required.")]
        public string Address { get; set; }
        [Required(ErrorMessage = "City name is required.")]
        public string City { get; set; }
        [Required(ErrorMessage = "Zipcode is required.")]
        [RegularExpression(@"(^\d{5}$)|(^\d{9}$)|(^\d{5}-\d{4}$)", ErrorMessage = "zipcode is not valid")]
        public string ZipCode { get; set; }
    }
}

Final-kk/AlbumsApp/Controllers/StudioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using AlbumsApp.Models;
using Microsoft.AspNetCore.Identity;

namespace AlbumsApp.Controllers
{
    public class StudioController : Controller
    {
        
        public StudioController(AlbumsDbContext albumContext, UserManager<User> userMngr, SignInManager<User> signInMngr)
        {
            signInManager = signInMngr;
            userManager = userMngr;
            _albumsDbContext = albumContext;
        }

        public IActionResult List()
        {
            List<Studio> studios = _albumsDbContext.Studios.OrderBy(s => s.Name).ToList();
            return View(studios);
        }

        [HttpGet]
        public IActionResult Add()
        {
            if (!signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Login", "Account");
            }
            return View(new Studio());
        }

        [HttpPost]
        public IActionResult Add(Studio studio)
        {
            if (ModelState.IsValid)
            {
                _albumsDbContext.Studios.Add(studio);
                _albumsDbContext.SaveChanges();

                return RedirectToAction("List", "Album");
            }

            return View(studio);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Login", "Account");
            }
            Studio studio = _albumsDbContext.Studios.Where(a => a.StudioId == id).FirstOrDefault();
            return View(studio);
        }

        [HttpPost]
        public IActionResult Edit(Studio studio)
        {
            if (ModelState.IsValid)
            {
                _albumsDbContext.Studios.Update(studio);
                _albumsDbContext.SaveChanges();

                return RedirectToAction("List", "Album");
            }
            return View(studio);
        }

        private AlbumsDbContext _albumsDbContext;
        private UserManager<User> userManager;
        private SignInManager<User> signInManager;
    }
}

Final-kk/AlbumsApp/Views/Studio/Add.cshtml
@model Studio

@{
    string title = "Add a new studio";
    ViewBag.Title = title;
}

<h2>@title</h2>

<form asp-controller="Studio" asp-action="Add" method="post" enctype="application/x-www-form-urlencoded">
    <partial name="_StudioFormFieldsPartial" model="@Model" />

    <input type="submit" value="Add studio" class="btn btn-primary" />
    <a asp-controller="Album" asp-action="List" class="btn btn-primary">Cancel</a>
</form>

Final-kk/AlbumsApp/Views/Studio/Edit.cshtml
@model Studio

@{
    string title = "Edit a studio";
    ViewBag.Title = title;
}

<h2>@title</h2>

<form asp-controller="Studio" asp-action="Edit" asp-route-id="@Model.StudioId" method="post" enctype="application/x-www-form-urlencoded">
    <partial name="_StudioFormFieldsPartial" model="@Model" />

    <input type="hidden" asp-for="StudioId" />

    <input type="submit" value="Update studio" class="btn btn-primary" />
    <a asp-controller="Album" asp-action="List" class="btn btn-primary">Cancel</a>
</form>

Final-kk/AlbumsApp/Views/Studio/List.cshtml
@model List<Studio>

@{
    string title = "All Studios";
}

<h3>@title</h3>
<partial name="AddLinks" />
@*<a asp-controller="Album" asp-action="Add">Add a new album</a>
<span class="linkSpacer">|</span>
<a asp-controller="Studio" asp-action="Add">Add a new studio</a>*@

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Website</th>
            <th>Address</th>
            <th>City</th>
            <th>Zip/Postal code</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var studio in Model)
        {
            <tr>
                <td>@studio.Name</td>
                <td><a target="_blank" href="@studio.Url">@studio.Url</a></td>
                <td>@studio.Address</td>
                <td>@studio.City</td>
                <td>@studio.ZipCode</td>
                <td>
                    <a asp-controller="Studio" asp-action="Edit" asp-route-id="@studio.StudioId">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>